apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: basic-cluster
  region: us-east-1
nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key



      ## to delete cluster "eksctl delete cluster -f cluster.yaml --wait --disable-nodegroup-eviction"


       ## to create cluster "eksctl create cluster -f cluster.yaml"