apiVersion: apps/v1
kind: Deployment
metadata:
  name: nopdeploy
  labels:
    app: nop
spec:
  minReadySeconds: 1
  replicas: 1
  selector:
    matchLabels:
      app: nop
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: noppod
      labels:
        app: nop
    spec:
      containers:
        - name: nopcommerce
          image: manugatla/nopcommerce
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_SERVER
              value: mysql
      # nodeSelector:
      #   disktype: ssd
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: disktype
      #               operator: In
      #               values: 
      #                 - ssd
      # tolerations:
      #   - key: disktype
      #     operator: Equal
      #     value: ssd
      #     effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: nopsvc
spec:
  type: LoadBalancer
  selector:
    app: nop
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 5000

  
  
              
            

          
      
