apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-of-life
spec:
  minReadySeconds: 1
  replicas: 3
  selector:
    matchLabels:
      app: gol
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: gol-pod
      labels:
        app: gol
    spec:
      containers:
        - name: gol-cont
          image: manugatla/gameoflife
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: gol-svc
spec:
  type: LoadBalancer
  selector:
    app: gol
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8080 