apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - name: sql-pod
      image: mysql
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: sql-config
            optional: false